[main]
shell=/usr/bin/zsh
font=Fira Code:size=13
pad=4x4

[colors]
background=220938
foreground=e6d6ff

# Black
regular0=3d2f4a
bright0=7a5a9a

# Red
regular1=a84d72
bright1=c46a8f

# Green
regular2=6a5a9a
bright2=8a7aba

# Yellow
regular3=a878a8
bright3=c496c4

# Blue
regular4=6a4b86
bright4=b39ee0

# Magenta
regular5=c7a6ff
bright5=e6d6ff

# Cyan
regular6=7a6e96
bright6=9a8eb6

# White
regular7=dcd3e8
bright7=f6f0fb
